[project]
name = "vtai"
version = "0.1.0"
description = "VT.ai - Simple LLM chat frontend"
authors = [{ name = "Vinh Nguyen", email = "" }]
dependencies = [
    "litellm>=1.35.17",
    "chainlit>=1.0.504",
    "google-generativeai>=0.5.2",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/vtai"]
